viyyoor/web/forms/accounts.py
"""
Created on Oct 13, 2013

@author: boatkrap
"""

from wtforms import validators
from wtforms import fields

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from flask_mongoengine.wtf import model_form

from .. import models
from .fields import TagListField


def validate_email(form, field):
    # user = models.User.objects(email=field.data).first()
    user = None
    if user is not None:
        raise validators.ValidationError(
            "This email: %s is available on system" % field.data
        )


def validate_username(form, field):

    if field.data.lower() in [
        "admin",
        "administrator",
        "lecturer",
        "staff",
        "moderator",
        "member",
        "anonymous",
        "pumbaa",
        "master",
        "student",
        "user",
        "manager",
        "coe",
        "teacher",
        "psu",
    ]:
        raise validators.ValidationError(
            "This username: %s is not allowed" % field.data
        )

    user = None
    # user = models.User.objects(username=field.data).first()

    # request = get_current_request()
    # request_user = request.user
    # if request_user == user:
    #     return

    if user is not None:
        raise validators.ValidationError(
            "This user: %s is available on system" % field.data
        )


BaseProfileForm = model_form(
    models.User,
    FlaskForm,
    exclude=[
        "created_date",
        "updated_date",
        "last_login_date",
        "picture",
        "roles",
        "status",
        "username",
        "resources",
        "other_ids",
        "user_setting",
    ],
    field_args={
        "title": {"label": "Title"},
        "first_name": {"label": "First Name"},
        "last_name": {"label": "Last Name"},
        "title_th": {"label": "Thai Title"},
        "first_name_th": {"label": "Thai First Name"},
        "last_name_th": {"label": "Thai Last Name"},
        "biography": {"label": "Biography"},
        "email": {"label": "Email"},
        "citizen_id": {"label": "Citizen ID"},
    },
)


class ProfileForm(BaseProfileForm):
    pic = fields.FileField(
        "Picture", validators=[FileAllowed(["png", "jpg"], "allow png and jpg")]
    )
    other_ids = TagListField("Other IDs")


BaseUserForm = model_form(
    models.User,
    FlaskForm,
    exclude=[
        "created_date",
        "updated_date",
        "last_login_date",
        "picture",
        "roles",
        # "status",
        "resources",
        "user_setting",
    ],
    field_args={
        "title": {"label": "Title"},
        "first_name": {"label": "First Name"},
        "last_name": {"label": "Last Name"},
        "title_th": {"label": "Thai Title"},
        "first_name_th": {"label": "Thai First Name"},
        "last_name_th": {"label": "Thai Last Name"},
        "biography": {"label": "Biography"},
        "email": {"label": "Email"},
        "username": {"label": "Username"},
        "status": {"label": "Status"},
        "citizen_id": {"label": "Citizen ID"},
    },
)


class UserForm(BaseUserForm):
    roles = TagListField("Roles", default=["user"])


BaseUserSettingForm = model_form(
    models.users.UserSetting,
    FlaskForm,
    exclude=["updated_date"],
    field_args={
        "organization": {"label": "Organization", "label_modifier": lambda o: o.name},
    },
)


class UserSettingForm(BaseUserSettingForm):
    organizations = fields.SelectMultipleField("Organizations")

class SelectOrganizationForm(BaseUserSettingForm):
    current_organization = fields.SelectField("Select Organization")

viyyoor/web/views/accounts.py
import datetime
import mongoengine as me
import markdown

from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    current_app,
    send_file,
    abort,
)
from flask_login import login_user, logout_user, login_required, current_user

from .. import models
from .. import oauth2
from .. import forms

module = Blueprint("accounts", __name__)


def get_user_and_remember():
    client = oauth2.oauth2_client
    result = client.principal.get("me")
    data = result.json()

    user = models.User.objects(
        me.Q(username=data.get("username", "")) | me.Q(email=data.get("email", ""))
    ).first()
    if not user:
        user = models.User(
            id=data.get("id"),
            first_name=data.get("first_name").title(),
            last_name=data.get("last_name").title(),
            email=data.get("email"),
            username=data.get("username"),
            status="active",
        )
        roles = []
        for role in ["student", "lecturer", "staff"]:
            if role in data.get("roles", []):
                roles.append(role)

        user.save()

    if user:
        login_user(user, remember=True)


@module.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))

    if "next" in request.args:
        session["next"] = request.args.get("next", None)

    return render_template("/accounts/login.html")


@module.route("/login-engpsu")
def login_engpsu():
    client = oauth2.oauth2_client
    scheme = request.environ.get("HTTP_X_FORWARDED_PROTO", "http")
    redirect_uri = url_for("accounts.authorized_engpsu", _external=True, _scheme=scheme)
    response = client.engpsu.authorize_redirect(redirect_uri)
    return response


@module.route("/authorized-engpsu")
def authorized_engpsu():
    client = oauth2.oauth2_client
    try:
        token = client.engpsu.authorize_access_token()
    except Exception as e:
        print(e)
        return redirect(url_for("accounts.login"))

    userinfo_response = client.engpsu.get("userinfo")
    userinfo = userinfo_response.json()

    user = models.User.objects(
        me.Q(username=userinfo.get("username", ""))
        | me.Q(email=userinfo.get("email", ""))
    ).first()

    if not user:
        user = models.User(
            username=userinfo.get("username"),
            email=userinfo.get("email"),
            first_name=userinfo.get("first_name").title(),
            last_name=userinfo.get("last_name").title(),
            status="active",
        )
        user.resources[client.engpsu.name] = userinfo
        # if 'staff_id' in userinfo.keys():
        #     user.roles.append('staff')
        # elif 'student_id' in userinfo.keys():
        #     user.roles.append('student')
        if userinfo["username"].isdigit():
            user.roles.append("student")
        elif (
            "COE_LECTURERS" in current_app.config
            and userinfo["username"] in current_app.config["COE_LECTURERS"]
        ):
            user.roles.append("lecturer")
            user.roles.append("CoE-lecturer")
        elif (
            "COE_STAFFS" in current_app.config
            and userinfo["username"] in current_app.config["COE_STAFFS"]
        ):
            user.roles.append("staff")
            user.roles.append("CoE-staff")

        else:
            user.roles.append("staff")

        # if userinfo['username'].isdigit():
        #     project = models.Project.objects(
        #             student_ids=userinfo['username']).first()

        #     if project and user not in project.owners:
        #         project.owners.append(user)
        #         project.save()
    else:
        user.resources[client.engpsu.name] = userinfo
        user.last_login_date = datetime.datetime.now()

    user.save()

    login_user(user)

    oauth2token = models.OAuth2Token(
        name=client.engpsu.name,
        user=user,
        access_token=token.get("access_token"),
        token_type=token.get("token_type"),
        refresh_token=token.get("refresh_token", None),
        expires=datetime.datetime.utcfromtimestamp(token.get("expires_in")),
    )
    oauth2token.save()

    next_uri = session.get("next", None)
    if next_uri:
        session.pop("next")
        return redirect(next_uri)

    return redirect(url_for("dashboard.index"))


@module.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("site.index"))


@module.route("/accounts/<user_id>")
def profile(user_id):
    user = models.User.objects.get(id=user_id)

    return render_template(
        "/accounts/index.html",
        user=user,
    )


@module.route("/accounts", methods=["GET", "POST"])
@login_required
def index():
    biography = ""
    if current_user.biography:
        biography = markdown.markdown(current_user.biography)

    form = forms.accounts.SelectOrganizationForm(obj=current_user.user_setting)
    form.current_organization.choices = [
        (str(o.id), o.name) for o in current_user.organizations
    ]

    if form.validate_on_submit():
        current_user.user_setting.current_organization = (
            models.Organization.objects.get(id=form.current_organization.data)
        )
        current_user.save()
        return redirect(url_for("accounts.index"))

    current_organization = current_user.user_setting.current_organization
    if current_organization:
        form.current_organization.data = str(current_organization.id)
    return render_template(
        "/accounts/index.html", user=current_user, biography=biography, form=form
    )


@module.route("/accounts/edit-profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = forms.accounts.ProfileForm(obj=current_user, pic=current_user.picture)
    if not form.validate_on_submit():
        return render_template("/accounts/edit-profile.html", form=form)

    user = current_user._get_current_object()
    form.populate_obj(user)

    if form.pic.data:
        if user.picture:
            user.picture.replace(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )
        else:
            user.picture.put(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )

    user.updated_date = datetime.datetime.now()
    user.save()

    return redirect(url_for("accounts.index"))


@module.route("/accounts/<user_id>/picture/<filename>", methods=["GET", "POST"])
def picture(user_id, filename):
    user = models.User.objects.get(id=user_id)

    if not user or not user.picture or user.picture.filename != filename:
        return abort(403)

    response = send_file(
        user.picture,
        download_name=user.picture.filename,
        mimetype=user.picture.content_type,
    )
    return response


@module.route(
    "/accounts/<user_id>/add-signature",
    methods=["GET", "POST"],
    defaults={"signature_id": None},
)
@module.route("/accounts/<user_id>/signatures/<signature_id>", methods=["GET", "POST"])
def add_or_edit_signature(user_id, signature_id):
    user = models.User.objects.get(id=user_id)

    form = forms.signatures.SignatureForm()
    if signature_id:
        signature = models.Signature.objects(id=signature_id).first()
        form = forms.signatures.SignatureForm(obj=signature)

    if not form.validate_on_submit():
        return render_template(
            "/accounts/add-signature.html",
            form=form,
        )

    if not signature_id:
        signature = models.Signature(
            owner=current_user._get_current_object(),
            ip_address=request.remote_addr,
        )

        signature.file.put(
            form.digital_signature_file.data,
            filename=form.signature_file.data.filename,
            content_type=form.signature_file.data.content_type,
        )
    else:
        signature.file.replace(
            form.signature_file.data,
            filename=form.signature_file.data.filename,
            content_type=form.signature_file.data.content_type,
        )

    signature.last_updated_by = current_user._get_current_object()
    signature.updated_date = datetime.datetime.now()
    signature.ip_address = request.remote_addr
    signature.save()

    return redirect(url_for("accounts.profile", user_id=user_id))


@module.route("/change_organization/<organization_id>")
def change_organization(organization_id):
    user = current_user._get_current_object()
    organization = models.Organization.objects.get(id=organization_id)
    if organization in user.organizations:
        user.user_setting.current_organization = organization
        user.user_setting.updated_date = datetime.datetime.now()
        user.save()

    return redirect(url_for("dashboard.index"))

viyyoor/web/templates/accounts/add-digital-signature.html
{% extends '/accounts/index.html' %}
{% import '/base/error-handler.html' as eh %}
{% import '/base/html-renderer.html' as renderer %}

{% block title %}
  {{ current_user.first_name }} {{ current_user.last_name }}
{% endblock %}

{% block breadcrumbs %}
{{ super() }}
<i class="right angle icon divider"></i>
<div class="active section">Add Digital Signature</div>
{% endblock %}

{% block content %}
<div class="ui content">
  <div class="ui segment">
    <h2>Add Digital Signature</h2>
    <form method="POST" class="ui form" enctype="multipart/form-data">
      {{ form.csrf_token }}
      {{ renderer.render_fileinput(form.digital_signature_file) }}
      <button name="create" type="submit" class="ui primary button">Add</button>
    </form>
    {% if form.errors | length > 0 %}
      <div class="ui message negative">
        <ul>
          {% for error, msg in form.errors.items() %}
            <li>{{ error }} {{ msg | join('') }}</li>
          {% endfor %}
        </ul>
    </div>
  {% endif %}
  </div>
</div>

<div class="row">
  <div class="col s12">
  </div>
</div>

{% endblock content %}

{% block additional_js %}
    <script type="text/javascript">
      $(".attach-file-digital_signature_file").click(function() {
        $(this).parent().find("#digital_signature_file").click();
      });

      $('#digital_signature_file')
      .on('change', function(e) {
        var name = e.target.files[0].name;
        $('.attach-file-digital_signature_file', $(e.target).parent()).val(name);
      });
    </script>

{% endblock additional_js %}

viyyoor/web/templates/accounts/add-signature.html
{% extends '/accounts/index.html' %}
{% import '/base/error-handler.html' as eh %}
{% import '/base/html-renderer.html' as renderer %}

{% block title %}
  {{ current_user.first_name }} {{ current_user.last_name }}
{% endblock %}

{% block breadcrumbs %}
{{ super() }}
<i class="right angle icon divider"></i>
<div class="active section">Add Signature Image</div>
{% endblock %}

{% block content %}
<div class="ui content">
  <div class="ui segment">
    <h2>Add Digital Signature</h2>
    <form method="POST" class="ui form" enctype="multipart/form-data">
      {{ form.csrf_token }}
      {{ renderer.render_fileinput(form.signature_file) }}
      <button name="create" type="submit" class="ui primary button">Add</button>
    </form>
    {% if form.errors | length > 0 %}
      <div class="ui message negative">
        <ul>
          {% for error, msg in form.errors.items() %}
            <li>{{ error }} {{ msg | join('') }}</li>
          {% endfor %}
        </ul>
    </div>
  {% endif %}
  </div>
</div>

<div class="row">
  <div class="col s12">
  </div>
</div>

{% endblock content %}

{% block additional_js %}
    <script type="text/javascript">
      $(".attach-file-signature_file").click(function() {
        $(this).parent().find("#signature_file").click();
      });

      $('#signature_file')
      .on('change', function(e) {
        var name = e.target.files[0].name;
        $('.attach-file-signature_file', $(e.target).parent()).val(name);
      });
    </script>

{% endblock additional_js %}

viyyoor/web/templates/accounts/edit-profile.html
{% extends '/accounts/index.html' %}
{% import '/base/error-handler.html' as eh %}
{% import '/base/html-renderer.html' as renderer %}

{% block title %}
  {{ current_user.title }} {{ current_user.first_name }} {{ current_user.last_name }}
{% endblock %}

{% block breadcrumbs %}
{{ super() }}
<i class="right angle icon divider"></i>
<div class="active section">Edit Profile</div>
{% endblock %}

{% block content %}
<div class="ui content">
  <div class="ui segment">
    <h2>Profile</h2>
    <form method="POST" class="ui form" enctype="multipart/form-data">
      {{ form.csrf_token }}
      <div class="three fields">
        {{ renderer.render_field(form.title) }}
        {{ renderer.render_field(form.first_name) }}
        {{ renderer.render_field(form.last_name) }}
      </div>
      <div class="three fields">
        {{ renderer.render_field(form.title_th) }}
        {{ renderer.render_field(form.first_name_th) }}
        {{ renderer.render_field(form.last_name_th) }}
      </div>
      <div class="two fields">
        {{ renderer.render_field(form.email) }}
        {{ renderer.render_fileinput(form.pic) }}
      </div>
      <div class="two fields">
        {{ renderer.render_field(form.citizen_id) }}
        {{ renderer.render_field(form.other_ids) }}
      </div>
      {{ renderer.render_field(form.biography) }}
      <a onclick="$('.modal.edit').modal('show')" class="ui primary icon button">
      Change
      </a>

      <div class="ui small modal edit">
        <div class="header">Edit Profile</div>
        <div class="content">
          <h4 class="ui headers" >
            Are you sure you want to edit <span class="ui primary text">{{ current_user.first_name }} {{ current_user.last_name }}</span> profile?
          </h4>
          <button class="ui right floated primary button" onclick="$('.ui.form').submit()" style="margin-bottom: 1em;">
            Edit
          </button>
          <button class="ui right floated button" onclick="$('.modal.edit').modal('hide')">Cancel</button>
        </div>
      </div>

    </form>
  </div>
</div>

<div class="row">
  <div class="col s12">
  </div>
</div>

{% endblock content %}

{% block additional_js %}
    <script type="text/javascript">
      $(".attach-file-pic").click(function() {
        $(this).parent().find("#pic").click();
      });

      $('#pic')
      .on('change', function(e) {
        var name = e.target.files[0].name;
        $('.attach-file-pic', $(e.target).parent()).val(name);
      });
    </script>

{% endblock additional_js %}

viyyoor/web/templates/accounts/index.html
{% import '/base/html-renderer.html' as renderer %}

{% if current_user.is_authenticated %}
  {% extends '/base/default-dashboard.html' %}
{% else %}
  {% extends '/base/default-page.html' %}
{% endif %}

{% block dashboard_title %}
Profile
{% endblock %}

{% block breadcrumbs %}
{% if request.endpoint == "accounts.index" %}
Accounts
{% else %}
<a href="{{ url_for('accounts.index') }}" class="breadcrumb">Accounts</a>
{% endif %}
{% endblock %}

{% block title %}
  {{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block content %}
<div class="ui container">

  {% if current_user.organizations %}
  <div class="ui segment">
    <div class="ui two column very relaxed grid">
      <div class="four wide column">
        <h2 class="ui header">Organization </h2>
      </div>
      <div class="column">
        <a class="ui blue labeled icon button" onclick="showHideForm()">
          Change Organization
          <i class="edit icon"></i>
        </a>
      </div>
    </div>
    <h3 class="ui blue header">
      {{ current_user.get_current_organization().name }}
    </h3> 
  </div>
  {% endif %}

  <div class="ui segment" id="ui-select-form" style="display: none">
    <form method="POST" class="ui form">
      {{ form.csrf_token }}
      {{ renderer.render_select(form.current_organization) }}
      <button name="submit" type="submit" class="ui labeled primary icon button"><i class="save icon"></i>Save</button>
      <a class="ui button" onclick="showHideForm()">Close</a>
    </form>
  </div>

  <div class="ui segment">
    <div class="ui two column very relaxed grid">
      <div class="four wide column center aligned">
        <h2 class="ui left aligned header">Profile</h2>
        <div class="ui small image">
          <img src="{{ user.get_picture() }}">
        </div>
      </div>

      <div class="column">
        {% if current_user.is_authenticated and current_user.id == user.id %}
          <a class="ui primary labeled icon button" href="{{ url_for('accounts.edit_profile') }}" title='Edit profile.'>Edit Profile <i class="edit icon"></i></a>
        {% endif %}
        <table class="ui single line table">
          <tbody>
            <tr>
              <td class="five wide">
                <div style="color: grey">NAME </div>
                {{ user.first_name }} {{ user.last_name }}
              </td>
              <td >
                <div style="color: grey">NAME_TH </div>
                {{ user.first_name_th + " " + user.last_name_th if user.first_name_th and user.last_name_th else "-" }}
              </td>
            </tr>
            <tr>
              <td>
                <div style="color: grey">EMAIL</div>
                {{ user.email }}
              </td>
              <td>
                <div style="color: grey">ROLE</div> 
                {% if current_user.get_current_organization_role()
                  and "admin" not in user.roles %}
                  <div class="ui label">
                    {{ current_user.get_current_organization_role().title() }}
                  </div>
                {% endif %}
                {% for role in user.roles %}
                  <div class="ui label">
                    {{ role }}
                  </div>
                {% endfor %}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  

  {% if 'endorser' in current_user.roles %}
  <div class="ui segment">
    <a class="ui primary icon button" href="{{ url_for('accounts.add_or_edit_signature', user_id=current_user.id) }}"><i class="signature icon"></i> Add Signature</a>
    <table class="ui celled table">
      <thead>
        <tr>
          <th>Filename</th>
          <th>Date</th>
          <th>Status</th>
          <th>Operation</th>
        </tr>
      </thead>
      <tbody>
        {% for signature in user.get_signatures() %}
        <tr>
          <td>{{ signature.file.filename }}</td>
          <td>{{ signature.created_date }}</td>
          <td>{{ signature.status }}</td>
          <td> 
            <a class="ui circular button primary icon" href="{{ url_for('accounts.add_or_edit_signature', user_id=user.id, signature_id=signature.id) }}"><i class="edit icon"></i></a>
            <a class="ui circular button primary icon" href="{{ url_for('admin.signatures.view', signature_id=signature.id) }}"><i class="eye icon"></i></a>
            <a class="ui circular button negative icon" href="{{ url_for('admin.signatures.delete', signature_id=signature.id) }}"><i class="trash icon"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endif %}

</div> {# end div container #}
{% endblock %}

{% block additional_js %}
<script>
  function showHideForm() {
    $(document.getElementById("ui-select-form")).transition('fade down')
  }
  $('.link.pop')
    .popup()
</script>
{% endblock %}

viyyoor/web/templates/accounts/login.html
{% extends "/base/default-page.html" %}

{% block title %}Log in{% endblock %}

{% block additional_head %}

  <style type="text/css">
    body > .grid {
      height: 100%;
    }
  </style>
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid" style="height: 70vh;">
  <div class="column">
    <h2 class="ui teal image header" style="font-size: 3em;">
      <img class="ui image" src="{{ url_for('static', filename='images/PSU-logo-300px.png') }}" width="200px">
      <div class="content">
        Login
      </div>
    </h2>
    <div>
      <div class="ui large vertical buttons" >
        <div class="row" style="padding: 10px;">
          <div class="column header" style="text-align: left;">
            <h3>For PSU Engineering Faculty Member</h3>
          </div>
        </div>
        <div class="row" style="padding-top: 5px;">
          <a class="ui labeled icon button primary huge" href="{{ url_for('accounts.login_engpsu') }}">
            <i class="user icon"></i>
            PSU Passport by Eng
          </a>
        </div>
        {% if 'GOOGLE' in config.LOGIN_PROVIDER %}
        <div class="row" style="padding: 10px;">
          <div class="column header" style="text-align: left;">
            <h3>For Participant</h3>
          </div>
        </div>
        <div class="row" style="padding-top: 5px;">
          <a class="ui  labeled icon red button huge" href="{{ url_for('loginpass.login', name='google') }}">
            <i class="google icon"></i>
            Google
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

viyyoor/web/templates/accounts/register.html
{% extends "/base/default-page.html" %}
{% block content %}
<style>
[type=checkbox]:not(:checked) {
  left: inherit;
  margin-top: 8px;
}
</style>
{% macro get_validate_class(errors) -%}
{%- set class_str = 'validate' -%}
{% if errors | count > 0 -%}
{% set class_str = class_str + ' ' + 'invalid' %}
{%- endif %}
{{- class_str -}}
{%- endmacro %}

{% macro get_error_messages(errors) -%}
{{ errors | join(', ') }}
{%- endmacro %}


<div class="row">
  <div class="col s12">
    <h3>Register</h3>
    {% if errors is not undefined %}
    <div class="card red lighten-5">
      <div class="card-content red-text text-darken-4">
        <span class="card-title">Errors</span>
          {% for error in errors %}
          <p>{{ error.detail }}</p>
          {% endfor %}
      </div>
    </div>

    {% endif %}
    <form method="post" action="{{request.path}}">
      {{ form.csrf_token }}
      <div class="row"> 
        <div class="input-field col s12">
          {{ form.username(class_=get_validate_class(form.username.errors)) }}
          {{ form.username.label(data_error=get_error_messages(form.username.errors)) }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.email(class_=get_validate_class(form.email.errors)) }}
          {{ form.email.label(data_error=get_error_messages(form.email.errors)) }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          {{ form.password(class_=get_validate_class(form.password.errors)) }}
          {{ form.password.label(data_error=get_error_messages(form.password.errors)) }}
        </div>
        <div class="input-field col s6">
          {{ form.password_conf(class_=get_validate_class(form.password_conf.errors)) }}
          {{ form.password_conf.label(data_error=get_error_messages(form.password_conf.errors)) }}
        </div>
      </div> 
      <div class="row">
        <div class="input-field col s6">
          {{ form.first_name(class_=get_validate_class(form.first_name.errors)) }}
          {{ form.first_name.label(data_error=get_error_messages(form.first_name.errors)) }}
        </div>
        <div class="input-field col s6">
          {{ form.last_name(class_=get_validate_class(form.last_name.errors)) }}
          {{ form.last_name.label(data_error=get_error_messages(form.last_name.errors)) }}
        </div>
      </div>
      <div class="row" style="padding-top:10px;">
        <div class="col s12">
          {{ form.agree_term(class_="filled-in "+get_validate_class(form.agree_term.errors)) }}
          {{ form.agree_term.label(text='Agree with terms and conditions?', data_error=get_error_messages(form.agree_term.errors)) }} 
          <span class="red-text">{{ get_error_messages(form.agree_term.errors) }}</span>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <button class="btn" type="submit">Register</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

viyyoor/web/templates/accounts/register_success.html
{% extends "/base/default-page.html" %}

{% block title %}Register Success{% endblock %}

{% block additional_head %}
<script type="text/javascript">
  console.log('script update')
  setTimeout(function () {
       window.location.href = "{{ url_for('accounts.login') }}";
  }, 2000);
</script>
{% endblock %}

{% block content %}

<div class="row" style="min-height: 40vh;">
  <div class="col s12">
    <h3>Register Success</h3>
    Going to <a href="{{ url_for('accounts.login') }}">login</a> page!
  </div>
</div>

{% endblock %}