viyyoor/web/forms/organizations.py
from flask_mongoengine.wtf import model_form
from flask_wtf import FlaskForm, file
from wtforms import fields, widgets, validators

from viyyoor import models

BaseLogoForm = model_form(
    models.Logo,
    FlaskForm,
    only=["logo_name"],
    field_args={
        "logo_name": {"label": "Logo Name"},
    },
)


class LogoForm(BaseLogoForm):
    uploaded_logo_file = file.FileField(
        "Logo File",
        validators=[
            file.FileAllowed(["png", "jpg"], "รับเฉพาะไฟล์ png เเละ jpg เท่านั้น"),
        ],
    )

viyyoor/web/views/classes.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    Response,
    send_file,
    request,
    current_app,
)
from flask_login import current_user, login_required
import datetime
from urllib import parse

from viyyoor import models
from .. import forms
from .. import acl
from .. import redis_rq

from viyyoor.utils import digital_signature_utils
from viyyoor.utils import certificate_utils

module = Blueprint(
    "classes",
    __name__,
    url_prefix="/classes",
)


@module.route("/")
@login_required
def index():
    enrollments = models.Enrollment.objects(user=current_user._get_current_object())
    return render_template("/classes/index.html", enrollments=enrollments)


@module.route("/<class_id>")
@login_required
def view(class_id):
    class_ = models.Class.objects.get(id=class_id)
    if "admin" in current_user.roles or "endorse" in current_user.roles:
        return render_template("/classes/view_endorse.html", class_=class_)

    return render_template("/classes/view.html", class_=class_)


@module.route("/<class_id>/endorse", methods=["GET", "POST"])
@acl.roles_required("endorser")
def endorse(class_id):
    class_ = models.Class.objects.get(id=class_id)
    # certificates = models.Certificate.objects(class_=class_, status="prerelease")
    # form = forms.classes.EndorsementForm()
    # if not form.validate_on_submit():
    #     return render_template(
    #         "/classes/endorse.html", form=form, class_=class_, certificates=certificates
    #     )

    certificates = models.Certificate.objects(class_=class_, status="prerelease")

    endorsers = class_.get_endorsers_by_user(current_user._get_current_object())
    if not len(endorsers):
        return redirect(url_for("dashboard.index"))

    for certificate in certificates:
        # sign signature hear1
        # sign_digital_signature(user, certificate, password)
        endorsement = models.Endorsement(
            endorser=current_user._get_current_object(),
            ip_address=request.remote_addr,
        )

        for endorser in endorsers:
            certificate.endorsements[endorser.endorser_id] = endorsement

        check_approval = True
        for key, endorser in class_.endorsers.items():
            if endorser.endorser_id not in certificate.endorsements:
                check_approval = False
            elif (
                endorser.endorser_id in certificate.endorsements
                and endorser.user
                != certificate.endorsements[endorser.endorser_id].endorser
            ):
                check_approval = False

            if not check_approval:
                break

        if check_approval:
            certificate.status = "signing"

        certificate.updated_date = datetime.datetime.now()
        certificate.save()

    job = redis_rq.redis_queue.queue.enqueue(
        digital_signature_utils.sign_certificates,
        args=(class_id, current_app.config),
        job_id=f"endorsements_certificates_{class_.id}",
        timeout=600,
        job_timeout=600,
    )

    return redirect(url_for("dashboard.index"))


@module.route("/<class_id>/certificate/<participant_id>.<extension>")
# @login_required
def render_certificate(class_id, participant_id, extension):
    response = Response()
    response.status_code = 404

    class_ = models.Class.objects.get(id=class_id)
    participant = class_.get_participant(participant_id)
    certificate_template = class_.certificate_templates.get(participant.group)

    if not certificate_template:
        return response

    class Organization:
        authenticity_text = current_app.config.get("DEFAULT_AUTHENTICITY_TEXT")

    class_.organization = Organization

    image_io = certificate_utils.render_certificate(
        class_,
        participant_id,
        extension,
        validated_url_template=request.host_url[:-1]
        + parse.unquote(
            url_for("certificates.view", certificate_id="{certificate_id}")
        ),
    )

    if extension in ["png", "svg"]:
        mimetype = f"image/{extension}"
    elif extension == "pdf":
        mimetype = "application/pdf"

    response = send_file(
        image_io,
        download_name=f"{class_.id}-{participant_id}.{extension}",
        # as_attachment=True,
        mimetype=mimetype,
    )

    return response

viyyoor/web/views/organization.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    send_file,
    Response,
)
from flask_login import current_user, login_required

import datetime

from viyyoor.web import acl, forms
from viyyoor import models


module = Blueprint("organizations", __name__, url_prefix="/organizations")


@module.route("/")
def index():
    organizations = models.Organization.objects(
        status="active",
    )
    return render_template(
        "/admin/organizations/index.html",
        now=datetime.datetime.now,
        organizations=organizations,
    )


@module.route("/<organization_id>")
@acl.roles_required("admin")
def view(organization_id):
    organization = models.Organization.objects.get(
        id=organization_id,
        status="active",
    )
    logos = models.CertificateLogo.objects()
    classes = models.Class.objects(organization=organization, status="active")
    return render_template(
        "/admin/organizations/view.html",
        logos=logos,
        organization=organization,
        classes=classes,
    )


@module.route("/logos/<logo_id>/download/<filename>")
def download_logo(logo_id, filename):
    response = Response()
    response.status_code = 404
    logo = models.CertificateLogo.objects.get(id=logo_id)

    if logo:
        response = send_file(
            logo.logo_file,
            download_name=filename,
            mimetype=logo.logo_file.content_type,
        )

    return response

viyyoor/web/views/organizations.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    send_file,
    Response,
)
from flask_login import current_user, login_required

import datetime

from viyyoor.web import acl, forms
from viyyoor import models


module = Blueprint("organizations", __name__, url_prefix="/organizations")


@module.route("/")
def index():
    organizations = models.Organization.objects(
        status="active",
    )
    return render_template(
        "/organizations/index.html",
        now=datetime.datetime.now,
        organizations=organizations,
    )


@module.route("/<organization_id>")
@acl.organization_roles_required("admin", "endorser", "staff")
def view(organization_id):
    organization = models.Organization.objects.get(
        id=organization_id,
        status="active",
    )
    logos = models.Logo.objects(organization=organization)
    classes = models.Class.objects(organization=organization, status="active")
    return render_template(
        "/organizations/view.html",
        logos=logos,
        organization=organization,
        classes=classes,
    )


@module.route("/<organization_id>/edit", methods=["GET", "POST"])
@acl.organization_roles_required("admin")
def edit(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    form = forms.organizations.AdminOrganizationEditForm()

    if not form.validate_on_submit():
        form.name.data = organization.name
        form.description.data = organization.description
        return render_template(
            "/organizations/edit.html", organization=organization, form=form
        )

    form.populate_obj(organization)
    organization.save()

    return redirect(url_for("organizations.view", organization_id=organization_id))


@module.route("/logos/<logo_id>/download/<filename>")
def download_logo(logo_id, filename):
    response = Response()
    response.status_code = 404
    logo = models.Logo.objects.get(id=logo_id)

    if logo:
        response = send_file(
            logo.logo_file,
            download_name=filename,
            mimetype=logo.logo_file.content_type,
        )

    return response


@module.route(
    "/<organization_id>/logos/<logo_id>/set_as_organization_logo", methods=["POST"]
)
@acl.organization_roles_required("admin")
def change_organization_logo(organization_id, logo_id):
    organization = models.Organization.objects.get(id=organization_id)
    old_logo = models.CertificateLogo.objects(
        organization=organization, marked_as_organization_logo=True
    ).first()
    if old_logo:
        old_logo.marked_as_organization_logo = False
        old_logo.last_updated_by = current_user._get_current_object()
        old_logo.updated_date = datetime.datetime.now()
        old_logo.save()

    new_logo = models.Logo.objects.get(id=logo_id)
    new_logo.marked_as_organization_logo = True
    new_logo.last_updated_by = current_user._get_current_object()
    new_logo.updated_date = datetime.datetime.now()
    new_logo.save()

    return redirect(url_for("organizations.view", organization_id=organization.id))


@module.route("/<organization_id>/classes", methods=["GET", "POST"])
@acl.organization_roles_required("admin", "endorser", "staff")
def view_classes(organization_id):
    organization = models.Organization.objects.get(
        id=organization_id,
        status="active",
    )
    classes = models.Class.objects(organization=organization, status="active")
    return render_template(
        "/organizations/classes.html",
        organization=organization,
        classes=classes,
    )


@module.route("/<organization_id>/logos", methods=["GET", "POST"])
@acl.organization_roles_required("admin", "endorser", "staff")
def view_logos(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    logos = models.Logo.objects(organization=organization)
    return render_template(
        "/organizations/logos.html",
        organization=organization,
        logos=logos,
    )


@module.route("/<organization_id>/users", methods=["GET", "POST"])
@acl.organization_roles_required("admin", "endorser", "staff")
def view_users(organization_id):
    organization = models.organizations.Organization.objects.get(id=organization_id)
    role = request.args.get("role")
    organization_user_roles = organization.get_users()
    if role not in ["all", None]:
        organization_user_roles = organization_user_roles.filter(role=role)
    if request.args.get("status") == "disactive":
        organization_user_roles = models.OrganizationUserRole.objects(
            status="disactive", organization=organization
        )

    org_user_forms = {}
    for u in organization_user_roles:
        org_user_forms[u.id] = forms.organizations.OrganizationRoleSelectionForm(obj=u)

    if request.args.get("user_role_id"):
        user_role = models.OrganizationUserRole.objects.get(
            id=request.args.get("user_role_id")
        )
        form = org_user_forms[user_role.id]
        if form.validate_on_submit():
            user_role.role = form.role.data
            user_role.save()
            return redirect(
                url_for(
                    "organizations.view_users",
                    organization_id=organization.id,
                    role=role,
                )
            )

    add_member_form = forms.organizations.OrgnaizationAddMemberForm()
    add_member_form.members.choices = [
        (str(u.id), u.get_fullname())
        for u in models.User.objects(organizations__nin=[organization])
    ]

    return render_template(
        "/organizations/users.html",
        organization=organization,
        organization_user_roles=organization_user_roles,
        role=role,
        org_user_forms=org_user_forms,
        add_member_form=add_member_form,
    )


@module.route("/<organization_id>/users/submit_add_members", methods=["POST"])
@acl.organization_roles_required("admin")
def submit_add_members(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    form = forms.organizations.OrgnaizationAddMemberForm()
    form.members.choices = [
        (str(u.id), u.get_fullname())
        for u in models.User.objects(organizations__nin=[organization])
    ]

    if not form.validate_on_submit():
        return redirect(
            url_for("organizations.view_users", organization_id=organization.id)
        )

    for u in form.members.data:
        user = models.User.objects.get(id=u)
        user.organizations.append(organization)
        if not user.get_current_organization():
            user.user_setting.current_organization = organization
        user.save()

        org_user = models.OrganizationUserRole(
            organization=organization,
            user=user,
            added_by=current_user._get_current_object(),
            last_modifier=current_user._get_current_object(),
        )
        org_user.save()

    return redirect(
        url_for("organizations.view_users", organization_id=organization.id)
    )


@module.route(
    "/<organization_id>/users/<organization_user_id>/<operator>",
    methods=["GET", "POST"],
)
@acl.organization_roles_required("admin")
def manage_user(organization_id, organization_user_id, operator):
    organization = models.Organization.objects.get(id=organization_id)
    organization_user = models.OrganizationUserRole.objects.get(id=organization_user_id)

    if operator == "deactivate":
        organization_user.status = "disactive"
    elif operator == "activate":
        organization_user.status = "active"
    elif operator == "delete":
        user = organization_user.user
        user.organizations.remove(organization)
        if user.get_current_organization() == organization:
            user.user_setting.current_organization = None
        user.save()
        organization_user.delete()

    organization_user.last_modifier = current_user._get_current_object()
    organization_user.updated_date = datetime.datetime.now()
    organization_user.last_ip_address = request.headers.get(
        "X-Forwarded-For", request.remote_addr
    )
    organization_user.save()

    print(operator, "user", organization_user.user.first_name)
    return redirect(
        url_for(
            "organizations.view_users",
            organization_id=organization.id,
            role="all",
        )
    )


@module.route("/<organization_id>/logos/add", methods=["GET", "POST"])
@acl.organization_roles_required("staff, admin")
def add_logo(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    logo = models.CertificateLogo()
    form = forms.organizations.OrganizationLogoForm()

    if not form.validate_on_submit():
        print(form.errors)
        return render_template(
            "/organizations/add-logo.html",
            organization=organization,
            form=form,
        )

    form.populate_obj(logo)

    if logo.logo_file:
        logo.logo_file.put(
            form.uploaded_logo_file.data,
            filename=form.uploaded_logo_file.data.filename,
            content_type=form.uploaded_logo_file.data.content_type,
        )

    else:
        logo.logo_file.replace(
            form.uploaded_logo_file.data,
            filename=form.uploaded_logo_file.data.filename,
            content_type=form.uploaded_logo_file.data.content_type,
        )

    logo.organization = organization
    logo.uploaded_by = current_user._get_current_object()
    logo.uploaded_date = datetime.datetime.now()
    logo.save()

    return redirect(
        url_for("organizations.view_logos", organization_id=organization_id)
    )


@module.route("/<organization_id>/<logo_id>/delete")
@acl.organization_roles_required("admin")
def delete_logo(organization_id, logo_id):
    organization = models.Organization.objects.get(id=organization_id)
    logo = models.CertificateLogo.objects.get(id=logo_id)
    logo.delete()

    return redirect(

viyyoor/web/templates/organizations/add-logo.html
{% extends "/organizations/logos.html" %}
{% import '/base/html-renderer.html' as renderer %}

{% block title %}{{ organization.name }}{% endblock %}

{% block breadcrumbs %}
{{ super() }}
Logo
{% endblock %}

{% block content %}
<div class="ui segment">
    <form method="POST", class="ui form" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ renderer.render_field(form.logo_name) }}
        {{ renderer.render_fileinput(form.uploaded_logo_file) }}
        
    <button name="Add Logo" type="submit" class="ui button primary">Add Logo</button>

    </form>
</div>
{% endblock %}

{% block additional_js %}
    {{ super() }}

    <script type="text/javascript">

    $(".attach-file-uploaded_logo_file").click(function() {
        $(this).parent().find("#uploaded_logo_file").click();
      });

      $('#uploaded_logo_file')
      .on('change', function(e) {
        var name = e.target.files[0].name;
        $('.attach-file-uploaded_logo_file', $(e.target).parent()).val(name);
      });
  

    </script>
{% endblock %}

viyyoor/web/templates/organizations/home.html
{% extends '/base/default-dashboard.html' %}
{% import '/base/organization-renderer.html' as org_renderer %}

{% block title %}{{ organization.name }}{% endblock %}

{% block dashboard_title %}
{{ organization.name }}
{# <a class="bug popup icon item" data-content="Edit This Page" href="{{ url_for('organizations.edit', organization_id=organization.id) }}">
    <h3><i class="edit icon"></i></h3>
</a>
#}
{% endblock %}

{% block breadcrumbs %}
{% if request.endpoint == 'organizations.view' %}
<div class="active section">{{ organization.name }}</div>
{% else %}
<a href="{{ url_for('organizations.view', organization_id=organization.id) }}" class="section">{{ organization.name }}</a>
<i class="right angle icon divider"></i>
{% endif %}
{% endblock %}



{% block content %}
{{ org_renderer.render_organization_dashboard_menu_bar(organization) }}

<div class="ui bottom attached segment">
	<div class="ui horizontal basic compact segments">
		<div class="ui very padded segment">
			<div class="ui horizontal grid">

				<h1 class="ui huge header">
					<img src="{{ organization.get_logo_picture() }}" width="120" height="120" style="object-fit: contain;">
					<div class="content">
						{{ organization.name }}
						<div class="sub header">{{ organization.description }}</div>
					</div>
				</h1>
				
				{% if current_user.is_admin_current_organization() %}
					<div class="ui top pointing dropdown " style="height: fit-content">
						<div class="ui tertiary blue button">
							<i class="blue settings icon"></i> SETTINGS 
						</div>
						<div class="menu">
							<a 	href="{{ url_for('organizations.edit', organization_id=organization.id) }}"
								class="item" style="height: fit-content">
								<i class="edit icon"></i>Edit
							</a>
							<a class="item" onclick="$('.icon.longer.modal').modal('show');">
								<i class="brush icon"></i>Change Logo
							</a>
							<div class="ui icon longer modal">
								<i class="close icon"></i>
								<div class="header">
									Change <span class="ui blue text">{{ organization.name }}</span> Logo
								</div>
								<div class="content">
									<div class="ui grid">
										{% for logo in logos %}
										<form class="form {{logo.id}}" method="POST" action="{{ url_for('organizations.change_organization_logo', organization_id=organization.id, logo_id=logo.id) }}">
											<i class="icons">
												<div class="three wide right aligned column">
													<img class="ui circular image" onclick="selectLogo('{{logo.id}}')" style="cursor: pointer; width: 128px; height: 128px; object-fit: contain"
													src="{{ url_for('organizations.download_logo', logo_id=logo.id, filename=logo.logo_file.filename) }}">
													<i id="{{logo.id}}" class="corner right bottom big {{'green check circle' if logo.marked_as_organization_logo else 'disabled grey circle outline'}} icon"></i>
												</div>
											</i>
										</form>
										{% endfor %}
									</div>	
								</div>
								<div class="actions">
									<button onclick="submitChangeLogo()" class="ui positive labeled icon button">
									<i class="check icon"></i>
									Save
									</button>
									<div class="ui deny button">
									Cancel
									</div>
								</div>
							</div>
						</div>
					</div>
			 	{% endif %}
			</div>
		</div>
		<div class="ui very padded segment">
			<h2 class="ui header">
				<i class="big certificate icon"></i>
				<div class="content">
					<div class="sub header">
						Quota Remaining
					</div>
					{{ organization.quota }}/{{ organization.quota }}
				</div>
			</h2>
		</div>
		<div class="ui very padded segment">
			<h2 class="ui header">
				<i class="big archive icon"></i>
				<div class="content">
					<div class="sub header">
						Class Amount
					</div>
					{{ classes.count() }}
				</div>
			</h2>
		</div>
	</div>
</div>

{% endblock %}

{% block additional_js %}
<script>
	function showDeleteModal(logo_id) {
        logo_id ?  $('.ui.small.modal.'+logo_id).modal('show') : $('.ui.small.modal').modal('hide') 
    ;
    }
	$('.link.pop').popup({
		delay: {
			show: 800,
	  }
	})
	function selectLogo(logo_id) {
		selected = "corner right bottom big green check circle icon"
		unselected = "corner right bottom big disabled grey circle outline icon"

		selected_logo = $('.green.check.circle.icon')
		if (selected_logo.length > 0) {
			selected_logo[0].className = unselected
		}
		document.getElementById(logo_id).className = selected
	}

	function submitChangeLogo() {
		selected_logo = $('.green.check.circle.icon')[0]
		console.log(selected_logo.id)
		console.log($('.form.'+selected_logo.id)[0].submit())
	}
</script>
{% endblock %}

viyyoor/web/templates/organizations/logos.html
{% extends '/organizations/view.html' %}
{% import '/base/organization-renderer.html' as org_renderer %}

{% block title %}{{ organization.name }}{% endblock %}

{% block dashboard_title %}
{{ organization.name }}
{# <a class="bug popup icon item" data-content="Edit This Page" href="{{ url_for('organizations.edit', organization_id=organization.id) }}">
    <h3><i class="edit icon"></i></h3>
</a>
#}
{% endblock %}

{% block breadcrumbs %}
    {{ super() }}
    {% if 'admin' in request.path %}
		{% if request.endpoint == 'admin.organizations.view_logos' %}
		<div class="active section">Logos</div>
		{% else %}
		<a href="{{ url_for('admin.organizations.view_logos', organization_id=organization.id) }}" class="section">{{ organization.name }}</a>
		<i class="right angle icon divider"></i>
		{% endif %}
	{% else %}
        {% if request.endpoint == 'organizations.view_logos' %}
        <div class="active section">Logos</div>
        {% else %}
        <a href="{{ url_for('organizations.view_logos', organization_id=organization.id) }}" class="section">Logos</a>
        <i class="right angle icon divider"></i>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
{{ org_renderer.render_organization_dashboard_menu_bar(organization) }}

<h2 class="ui header">
    Logos
    {% if current_user.is_admin_current_organization() %}
        <a class="ui primary tertiary icon right floated large button" href="{{ url_for('organizations.add_logo', organization_id=organization.id) }}">
            <i class="add icon"></i> Add Logo
        </a>
    {% endif %}
</h2>
<div class="ui divider"></div>
<div class="ui basic segment">
<div class="scroll">
        <div class="ui cards">
        {% for logo in logos %}
            <div class="card">
                <div class="ui image">
                    <img style="height: 128px; object-fit:contain" src="{{ url_for('organizations.download_logo', logo_id=logo.id, filename=logo.logo_file.filename) }}" />
                </div>

                <div class="ui content">
                    <div class="header">{{ logo.logo_name }}</div>
                    <div class="owner"><b>Owner : </b>{{ logo.uploaded_by.first_name }} {{ logo.uploaded_by.last_name }}</div>

                    {% if current_user.is_admin_current_organization() %}
                        <div class="right floated">
                            <a onclick="showDeleteModal('{{logo.id}}') "><i class="red trash icon"></i></a>
                        </div>
                        <div class="ui small modal {{logo.id}}">
                            <div class="header">Delete Logo</div>
                            <div class="content">
                                <h4 class="ui headers" >
                                    Are you sure you want to delete <span class="ui red text">{{ logo.logo_name }}</span> logo?
                                </h4>
                                <a class="ui right floated negative button" style="margin-bottom: 1em;" href="{{ url_for('organizations.delete_logo', organization_id=organization.id, logo_id=logo.id)}}">
                                    Delete</i>
                                </a>
                                <button class="ui right floated button" onclick="showDeleteModal()">Cancel</button>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>	
</div>
	
{% endblock %}

{% block additional_js %}
<script>
    function showDeleteModal(logo_id) {
        logo_id ?  $('.ui.small.modal.'+logo_id).modal('show') : $('.ui.small.modal').modal('hide') 
    ;
    }
	$('.link.pop').popup({
		delay: {
			show: 800,
	  }
	})
</script>
{% endblock %}

viyyoor/web/templates/organizations/view.html
{% if 'admin' in request.path %}
	{% extends '/admin/organizations/index.html' %}
{% else %}
	{% extends '/base/default-dashboard.html' %}
{% endif %}
{% import '/base/organization-renderer.html' as org_renderer %}

{% block title %}{{ organization.name }}{% endblock %}

{% block dashboard_title %}
{{ organization.name }}
{# <a class="bug popup icon item" data-content="Edit This Page" href="{{ url_for('organizations.edit', organization_id=organization.id) }}">
    <h3><i class="edit icon"></i></h3>
</a>
#}
{% endblock %}

{% block breadcrumbs %}
	{% if 'admin' in request.path %}
		{{ super() }}
		{% if request.endpoint == 'admin.organizations.view' %}
		<div class="active section">{{ organization.name }}</div>
		{% else %}
		<a href="{{ url_for('admin.organizations.view', organization_id=organization.id) }}" class="section">{{ organization.name }}</a>
		<i class="right angle icon divider"></i>
		{% endif %}
	{% else %}
		{% if request.endpoint == 'organizations.view' %}
		<div class="active section">{{ organization.name }}</div>
		{% else %}
		<a href="{{ url_for('organizations.view', organization_id=organization.id) }}" class="section">{{ organization.name }}</a>
		<i class="right angle icon divider"></i>
		{% endif %}
	{% endif %}
{% endblock %}



{% block content %}
{{ org_renderer.render_organization_dashboard_menu_bar(organization) }}
<div class="ui bottom attached segment">
	<div class="ui horizontal basic compact segments">
		<div class="ui very padded segment">
			<div class="ui horizontal grid">

				<h1 class="ui huge header">
					<img src="{{ organization.get_logo_picture() }}" width="120" height="120" style="object-fit: contain;">
					<div class="content">
						{{ organization.name }}
						<div class="sub header">{{ organization.description }}</div>
					</div>
				</h1>
				
				{% if current_user.is_admin_current_organization() %}
					<div class="ui top pointing dropdown " style="height: fit-content">
						<div class="ui tertiary blue button">
							<i class="blue settings icon"></i> SETTINGS 
						</div>
						<div class="menu">
							<a 	href="{{ url_for('organizations.edit', organization_id=organization.id) }}"
								class="item" style="height: fit-content">
								<i class="edit icon"></i>Edit
							</a>
							<a class="item" onclick="$('.icon.longer.modal').modal('show');">
								<i class="brush icon"></i>Change Logo
							</a>
							<div class="ui icon longer modal">
								<i class="close icon"></i>
								<div class="header">
									Change <span class="ui blue text">{{ organization.name }}</span> Logo
								</div>
								<div class="content">
									<div class="ui grid">
										{% for logo in logos %}
										<form class="form {{logo.id}}" method="POST" action="{{ url_for('organizations.change_organization_logo', organization_id=organization.id, logo_id=logo.id) }}">
											<i class="icons">
												<div class="three wide right aligned column">
													<img class="ui circular image" onclick="selectLogo('{{logo.id}}')" style="cursor: pointer; width: 128px; height: 128px; object-fit: contain"
													src="{{ url_for('organizations.download_logo', logo_id=logo.id, filename=logo.logo_file.filename) }}">
													<i id="{{logo.id}}" class="corner right bottom big {{'green check circle' if logo.marked_as_organization_logo else 'disabled grey circle outline'}} icon"></i>
												</div>
											</i>
										</form>
										{% endfor %}
									</div>	
								</div>
								<div class="actions">
									<button onclick="submitChangeLogo()" class="ui positive labeled icon button">
									<i class="check icon"></i>
									Save
									</button>
									<div class="ui deny button">
									Cancel
									</div>
								</div>
							</div>
						</div>
					</div>
			 	{% endif %}
			</div>
		</div>
		<div class="ui very padded segment">
			<h2 class="ui header">
				<i class="big certificate icon"></i>
				<div class="content">
					<div class="sub header">
						Quota Remaining
					</div>
					{{ organization.quota }}/{{ organization.quota }}
				</div>
			</h2>
		</div>
		<div class="ui very padded segment">
			<h2 class="ui header">
				<i class="big archive icon"></i>
				<div class="content">
					<div class="sub header">
						Class Amount
					</div>
					{{ classes.count() }}
				</div>
			</h2>
		</div>
	</div>
</div>

{% endblock %}

{% block additional_js %}
<script>
	function showDeleteModal(logo_id) {
        logo_id ?  $('.ui.small.modal.'+logo_id).modal('show') : $('.ui.small.modal').modal('hide') 
    ;
    }
	$('.link.pop').popup({
		delay: {
			show: 800,
	  }
	})
	function selectLogo(logo_id) {
		selected = "corner right bottom big green check circle icon"
		unselected = "corner right bottom big disabled grey circle outline icon"

		selected_logo = $('.green.check.circle.icon')
		if (selected_logo.length > 0) {
			selected_logo[0].className = unselected
		}
		document.getElementById(logo_id).className = selected
	}

	function submitChangeLogo() {
		selected_logo = $('.green.check.circle.icon')[0]
		console.log(selected_logo.id)
		console.log($('.form.'+selected_logo.id)[0].submit())
	}
</script>
{% endblock %}