viyyoor/web/views/accounts.py
import datetime
import mongoengine as me
import markdown

from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    current_app,
    send_file,
    abort,
)
from flask_login import login_user, logout_user, login_required, current_user

from .. import models
from .. import oauth2
from .. import forms

module = Blueprint("accounts", __name__)


def get_user_and_remember():
    client = oauth2.oauth2_client
    result = client.principal.get("me")
    data = result.json()

    user = models.User.objects(
        me.Q(username=data.get("username", "")) | me.Q(email=data.get("email", ""))
    ).first()
    if not user:
        user = models.User(
            id=data.get("id"),
            first_name=data.get("first_name").title(),
            last_name=data.get("last_name").title(),
            email=data.get("email"),
            username=data.get("username"),
            status="active",
        )
        roles = []
        for role in ["student", "lecturer", "staff"]:
            if role in data.get("roles", []):
                roles.append(role)

        user.save()

    if user:
        login_user(user, remember=True)


@module.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))

    if "next" in request.args:
        session["next"] = request.args.get("next", None)

    return render_template("/accounts/login.html")


@module.route("/login-engpsu")
def login_engpsu():
    client = oauth2.oauth2_client
    scheme = request.environ.get("HTTP_X_FORWARDED_PROTO", "http")
    redirect_uri = url_for("accounts.authorized_engpsu", _external=True, _scheme=scheme)
    response = client.engpsu.authorize_redirect(redirect_uri)
    return response


@module.route("/authorized-engpsu")
def authorized_engpsu():
    client = oauth2.oauth2_client
    try:
        token = client.engpsu.authorize_access_token()
    except Exception as e:
        print(e)
        return redirect(url_for("accounts.login"))

    userinfo_response = client.engpsu.get("userinfo")
    userinfo = userinfo_response.json()

    user = models.User.objects(
        me.Q(username=userinfo.get("username", ""))
        | me.Q(email=userinfo.get("email", ""))
    ).first()

    if not user:
        user = models.User(
            username=userinfo.get("username"),
            email=userinfo.get("email"),
            first_name=userinfo.get("first_name").title(),
            last_name=userinfo.get("last_name").title(),
            status="active",
        )
        user.resources[client.engpsu.name] = userinfo
        # if 'staff_id' in userinfo.keys():
        #     user.roles.append('staff')
        # elif 'student_id' in userinfo.keys():
        #     user.roles.append('student')
        if userinfo["username"].isdigit():
            user.roles.append("student")
        elif (
            "COE_LECTURERS" in current_app.config
            and userinfo["username"] in current_app.config["COE_LECTURERS"]
        ):
            user.roles.append("lecturer")
            user.roles.append("CoE-lecturer")
        elif (
            "COE_STAFFS" in current_app.config
            and userinfo["username"] in current_app.config["COE_STAFFS"]
        ):
            user.roles.append("staff")
            user.roles.append("CoE-staff")

        else:
            user.roles.append("staff")

        # if userinfo['username'].isdigit():
        #     project = models.Project.objects(
        #             student_ids=userinfo['username']).first()

        #     if project and user not in project.owners:
        #         project.owners.append(user)
        #         project.save()
    else:
        user.resources[client.engpsu.name] = userinfo
        user.last_login_date = datetime.datetime.now()

    user.save()

    login_user(user)

    oauth2token = models.OAuth2Token(
        name=client.engpsu.name,
        user=user,
        access_token=token.get("access_token"),
        token_type=token.get("token_type"),
        refresh_token=token.get("refresh_token", None),
        expires=datetime.datetime.utcfromtimestamp(token.get("expires_in")),
    )
    oauth2token.save()

    next_uri = session.get("next", None)
    if next_uri:
        session.pop("next")
        return redirect(next_uri)

    return redirect(url_for("dashboard.index"))


@module.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("site.index"))


@module.route("/accounts/<user_id>")
def profile(user_id):
    user = models.User.objects.get(id=user_id)

    return render_template(
        "/accounts/index.html",
        user=user,
    )


@module.route("/accounts", methods=["GET", "POST"])
@login_required
def index():
    biography = ""
    if current_user.biography:
        biography = markdown.markdown(current_user.biography)

    form = forms.accounts.SelectOrganizationForm(obj=current_user.user_setting)
    form.current_organization.choices = [
        (str(o.id), o.name) for o in current_user.organizations
    ]

    if form.validate_on_submit():
        current_user.user_setting.current_organization = (
            models.Organization.objects.get(id=form.current_organization.data)
        )
        current_user.save()
        return redirect(url_for("accounts.index"))

    current_organization = current_user.user_setting.current_organization
    if current_organization:
        form.current_organization.data = str(current_organization.id)
    return render_template(
        "/accounts/index.html", user=current_user, biography=biography, form=form
    )


@module.route("/accounts/edit-profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = forms.accounts.ProfileForm(obj=current_user, pic=current_user.picture)
    if not form.validate_on_submit():
        return render_template("/accounts/edit-profile.html", form=form)

    user = current_user._get_current_object()
    form.populate_obj(user)

    if form.pic.data:
        if user.picture:
            user.picture.replace(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )
        else:
            user.picture.put(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )

    user.updated_date = datetime.datetime.now()
    user.save()

    return redirect(url_for("accounts.index"))


@module.route("/accounts/<user_id>/picture/<filename>", methods=["GET", "POST"])
def picture(user_id, filename):
    user = models.User.objects.get(id=user_id)

    if not user or not user.picture or user.picture.filename != filename:
        return abort(403)

    response = send_file(
        user.picture,
        download_name=user.picture.filename,
        mimetype=user.picture.content_type,
    )
    return response


@module.route(
    "/accounts/<user_id>/add-signature",
    methods=["GET", "POST"],
    defaults={"signature_id": None},
)
@module.route("/accounts/<user_id>/signatures/<signature_id>", methods=["GET", "POST"])
def add_or_edit_signature(user_id, signature_id):
    user = models.User.objects.get(id=user_id)

    form = forms.signatures.SignatureForm()
    if signature_id:
        signature = models.Signature.objects(id=signature_id).first()
        form = forms.signatures.SignatureForm(obj=signature)

    if not form.validate_on_submit():
        return render_template(
            "/accounts/add-signature.html",
            form=form,
        )

    if not signature_id:
        signature = models.Signature(
            owner=current_user._get_current_object(),
            ip_address=request.remote_addr,
        )

        signature.file.put(
            form.digital_signature_file.data,
            filename=form.signature_file.data.filename,
            content_type=form.signature_file.data.content_type,
        )
    else:
        signature.file.replace(
            form.signature_file.data,
            filename=form.signature_file.data.filename,
            content_type=form.signature_file.data.content_type,
        )

    signature.last_updated_by = current_user._get_current_object()
    signature.updated_date = datetime.datetime.now()
    signature.ip_address = request.remote_addr
    signature.save()

    return redirect(url_for("accounts.profile", user_id=user_id))


@module.route("/change_organization/<organization_id>")
def change_organization(organization_id):
    user = current_user._get_current_object()
    organization = models.Organization.objects.get(id=organization_id)
    if organization in user.organizations:
        user.user_setting.current_organization = organization
        user.user_setting.updated_date = datetime.datetime.now()
        user.save()

    return redirect(url_for("dashboard.index"))

viyyoor/web/views/dashboard.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from viyyoor import models
import mongoengine as me
from viyyoor.web import acl

from .. import redis_rq

import datetime

module = Blueprint("dashboard", __name__, url_prefix="/dashboard")
subviews = []


def index_admin():
    now = datetime.datetime.now()
    endorser_positions = models.classes.ENDORSER_POSITIONS
    # queries = {
    #     f"endorsers__{ep[0]}__user": current_user._get_current_object()
    #     for ep in endorser_positions
    # }
    # print("q", queries)
    classes_set = set()
    endorsed_query = dict()
    endorses_query = dict()

    for ep in endorser_positions:
        queries = {f"endorsers__{ep[0]}__user": current_user._get_current_object()}
        endorsed_query[
            f"endorsements__{ep[0]}__endorser"
        ] = current_user._get_current_object()
        endorses_query[
            f"endorsements__{ep[0]}__endorser__ne"
        ] = current_user._get_current_object()
        sub_classes = models.Class.objects(**queries)
        classes_set.update(sub_classes)

    classes = list(classes_set)

    endorses_classes = models.Certificate.objects(
        status="prerelease", class___in=classes, **endorses_query
    ).distinct(field="class_")

    query_obj = None
    for k, v in endorsed_query.items():
        if query_obj:
            query_obj = query_obj | me.Q(**{k: v})
        else:
            query_obj = me.Q(**{k: v})

    endorsed_classes = models.Certificate.objects(
        query_obj, class___in=classes
    ).distinct(field="class_")

    endorses_classes.sort(key=lambda c: c.id, reverse=True)
    endorsed_classes.sort(key=lambda c: c.id, reverse=True)

    endorsed_jobs = dict()
    redis_queue = redis_rq.redis_queue
    for c in endorsed_classes:
        endorsed_jobs[str(c.id)] = redis_queue.get_job(
            f"endorsements_certificates_{c.id}"
        )

    return render_template(
        "/dashboard/index-admin.html",
        now=datetime.datetime.now(),
        endorses_classes=endorses_classes,
        endorsed_classes=endorsed_classes,
        endorsed_jobs=endorsed_jobs,
    )


def index_user():
    certificates = models.Certificate.objects(
        me.Q(common_id=current_user.username)
        | me.Q(common_id=current_user.citizen_id)
        | me.Q(common_id__in=current_user.other_ids)
    ).order_by("-id")
    now = datetime.datetime.now()
    return render_template(
        "/dashboard/index-user.html",
        now=datetime.datetime.now(),
        certificates=certificates,
    )


@module.route("/")
@login_required
def index():
    user = current_user._get_current_object()
    if "admin" in user.roles or "endorser" in user.roles:
        return index_admin()

    return index_user()


@module.route("/me")
@login_required
def show_my_certificates():
    return index_user()

viyyoor/web/views/sites.py
from flask import Blueprint, render_template, redirect, url_for
import datetime

from .. import models
from .. import caches

module = Blueprint("site", __name__)


@module.route("/")
@caches.cache.cached(timeout=600)
def index():
    now = datetime.datetime.now()
    class_count = models.Class.objects(status="active").count()
    certificate_count = models.Certificate.objects(status="completed").count()
    return render_template(
        "/sites/index.html",
        class_count=class_count,
        certificate_count=certificate_count,
    )

viyyoor/web/views/tags.py
from flask import Blueprint, render_template
from .. import models
from .. import caches

module = Blueprint('tags', __name__, url_prefix='/tags')


@module.route('/')
@caches.cache.cached(timeout=3600)
def index():
    # tags = models.Project.objects(public__ne='private').item_frequencies('tags', normalize=True)
    
    tags = models.Project.objects(public__ne='private').aggregate(
            [
                {
                    '$unwind': '$tags'
                },
                {
                    '$group': {
                        '_id': '$tags',
                        'count': {
                            '$sum': 1
                        },
                    },

                },

            ]
            )

    tags = {t['_id']:t['count'] for t in tags}

    return render_template(
            '/tags/index.html',
            tags=tags)


@module.route('/<name>')
def view(name):
    projects = models.Project.objects(tags__iexact=name, public__ne='private').order_by('-id')
    return render_template(
            '/tags/view.html',
            name=name,
            projects=projects)

viyyoor/web/templates/base/banner.html
    <div class="ui inverted vertical center aligned segment" style="background-color: rgb(25, 60, 108);">
        <div class="ui container grid row two columns">
          <div class="column">
            {#
            <i class="university icon massive"></i>
            #}
            <div>
              <img src="{{ url_for('static', filename='images/PSU-logo-white.png') }}">
            </div>
            <div style="padding-top: 1vh;">
              Department of Computer Engineering <br/>
              Faculty of Engineering <br/>
              Prince of Songkla University
            </div>
          </div>
          <div class="column">
            <div>
              <h1 class="ui huge inverted header" style="font-size:4em">{{ config.get('APP_TITLE') }} </h1>
              <h2>CoE Certification System, PSU, Please Login.</h2>
            </div>
            <div style="padding-top: 20px;">
              {% if not current_user.is_authenticated %}
                <a href="{{ url_for('accounts.login') }}" class="ui large primary button"><i class="sign in icon"></i>Login</a>
              {% else %}
                <a href="{{ url_for('dashboard.index') }}" class="ui large primary button"><i class="dashboard icon"></i>Dashboard</a>
                <a href="{{ url_for('accounts.logout') }}" class="ui large primary button"><i class="sign out icon"></i>Logout</a>
              {% endif %}
            </div>
          </div>
        </div>
    </div>

viyyoor/web/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>{% block title  %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') | add_date_url }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/color.css') | add_date_url }}">
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') | add_date_url }}"></script>
    <script src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') | add_date_url }}"></script>
    <style type="text/css">
      body {
        background-color: #DADADA;
      }
    </style>
    
    {% block default_head %}{% endblock %}
    {% block additional_head %}{% endblock %}
  </head>

  <body>
    {% block body %}{% endblock %}
  </body>
  {% block additional_js %}{% endblock %}
  {% include '/base/last-elements.html' %}
</html>

viyyoor/web/templates/base/default-dashboard.html
{% extends "/base/base-layout.html" %}
{% import '/base/organization-renderer.html' as org_renderer %}

{% block title %}
  {{ self.dashboard_title() }}
{% endblock %}

{% block default_head %}
  <style type="text/css">
    .ui.main.menu {
      display: none;
    }

    .full.height {
      display: flex;
      flex-direction: row;
    }

    .full.height > .toc .ui.menu {
      border-radius: 0;
      border-width: 0 1px 0 0;
      margin: 0;
      width: inherit;
      max-height: 100vh;
      height: 100vh;
      overflow: auto;
    }

    .toc {
      position: fixed;
      z-index: 1;
      width: 250px;
      flex: 0 0 auto;
      background-color: #1b1c1d;
    }

    .article {
      flex: 1 1 auto;
      min-width: 0px;
      margin-left: 250px;
    }

    .footer {
      border-top: 1px solid #DDDDDD !important;
      box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.08) inset !important;
      background-color: #FAFAFA !important;
      margin-top: 30px !important;
    }

    .main-content {
      margin: 20px !important;
      margin-top: 20px;
      min-height: 75vh;
    }

    .introduction {
      margin-left: 20px !important;
      border-bottom: 1px solid #DDDDDD;
      padding-bottom: 10px !important;
    }

    @media only screen and (max-width: 1050px) {
      .toc {
        display: none !important;
      }
      
      .article {
        margin-left: 0px;
      }

      .ui.main.menu {
        display: block !important;
      }
      .introduction {
        display: none !important;
      }
      .fixed.menu > .container {
        width: 100% !important;
    }

  </style>

  <script type="text/javascript">
  $(document).ready(function() {

      $('.left.sidebar.menu')
        .sidebar('attach events', '.launch.icon.item', 'show')
      ;
      $('.launch.icon.item')
        .removeClass('disabled')
      ;
 
      $('.ui.dropdown')
        .dropdown()
      ;
    })
  ;
  </script>

{% endblock default_head %}


{% block body %}
{# begin slide menu #}
<div class="ui vertical inverted sidebar large menu left">
   {% include "/base/toolbar-dashboard.html" with context %}
</div>
{# end slide menu #}

{# begin top bar mobile #}
<div class="ui fixed inverted main menu" style="background-color: rgb(25, 60, 108);">
  <div class="ui container">
    <a class="launch icon item">
      <i class="content icon"></i>
    </a>

    <div class="item">
      {% block dashboard_title %}{{ config.get('APP_TITLE') }} Dashboard{% endblock %}
    </div>

    {#
    <div class="right menu">
      
      <div class="vertically fitted borderless item">
        <iframe class="github" src="./Layouts _ Fomantic UI_files/github-btn.html" allowtransparency="true" frameborder="0" scrolling="0" width="100" height="20"></iframe>
      </div>
      
      <div class="item">
        <div class="ui hidden right aligned search input" id="search">
          <div class="ui transparent icon input">
            <input class="prompt" type="text" placeholder="Search...">
            <i class="inverted search link icon" data-content="Search UI"></i>
          </div>
          <div class="results"></div>
        </div>
      </div>

    </div>
    #}
  </div>
</div>
{# end top bar mobile #}

<div class="pusher">
  <div class="full height">

    {# begin default left side toc #}
    <div class="toc">
    <div class="ui vertical inverted large menu" style="background-color: rgb(25, 60, 108);">
      {% include "/base/toolbar-dashboard.html" with context %}
      </div>
    </div>
    {# end default left side toc #}
    {# end default left side toc #}

    {# begin main article #}
    <div class="article">
      <header>
        <div class="ui vertical dividing segment">
          <div class="introduction">
            <div class="ui basic segment" style="padding-bottom: 3.5em">
              <h1 class="ui left floated header">{{ self.dashboard_title() }}</h1>
              {{ org_renderer.render_organization_selection_menu(current_user) }}
            </div>
          </div>
        </div>
      </header>

      <main class="main-content">
        {%- if self.dashboard_title().lower() != 'dashboard' %}
        <div class="ui segment">
          <div class="ui big breadcrumb">
            {% block breadcrumbs %}
              <div class="active section">Dashboard</div>
            {% endblock %}
          </div>
        </div>
        {% endif -%}
{% block content %}{% endblock %}
      </main>

      <footer class="ui vertical footer segment">
{% include "/base/footer.html" %}
      </footer>
      
    </div>
    {# end main article #}

  </div>
{#
<footer class="ui vertical footer segment">
{% include "/base/footer.html" %}
</footer>
#}
</div>

{% endblock body %}

viyyoor/web/templates/base/default-page.html
{% extends "/base/base-layout.html" %}
{% block body %}

  <header> 
  {% block header %}
    {% if request.path == '/' %}
      <div style="padding-top: 10vh; background-color: rgb(25, 60, 108);" class="ui inverted segment vertical">
        {% include "/base/banner.html" %}
      </div>
    {% else %}
        {% include "/base/toolbar.html" %}
    {% endif %}
  {% endblock %}
  </header>

  <div class="container">
    <main>
      {% block content %}{% endblock content %}
    </main>
    <div class="ui inverted vertical segment" style="background-color: rgb(25, 60, 108);">
      <footer>
        {% include "/base/footer.html" %}
      </footer>
    </div>

  </div>
{% endblock body %}

viyyoor/web/templates/base/error-handler.html
{% macro get_validate_class(errors) -%}
{%- set class_str = 'validate' -%}
{% if errors | count > 0 -%}
{% set class_str = class_str + ' ' + 'invalid' %}
{%- endif %}
{{- class_str -}}
{%- endmacro %}

{% macro get_error_messages(errors) -%}
	{% if errors %}
  <div class="red lighten-5 red-text text-darken-4">
    {{ ', '.join(errors) }}
  </div>
  {% endif %}
{%- endmacro %}

viyyoor/web/templates/base/last-elements.html
{# include analytic or last elements #}

viyyoor/web/templates/base/organization-renderer.html
{% macro render_organization_selection_menu(current_user) %}
    {% if current_user.get_current_organization() %}
        {% set organization = current_user.get_current_organization() %}
        {% set logo = organization.get_logo() %}
        <h1 class="ui right floated header" >
            <div class="ui right top pointing dropdown">
                <div class="header" style="font-size: 16px;">
                    <div class="content" style="text-align: right; margin-right: 0.5em; vertical-align: 0.2em;">
                        {{ organization.name }}
                    </div>
                    <img src="{{ organization.get_logo_picture() }}" style="width: 45px; height: 45px; object-fit: contain">
                </div>
                <div class="menu">
                    <div class="ui center aligned basic segment" style="margin-top: 1em">
                        <img src="{{ organization.get_logo_picture() }}" style="width: 100px; height: 100px; object-fit: contain">
                        <br>
                        <a href="{{ url_for('organizations.view', organization_id=organization.id) }}">
                            <div class="ui basic segment">
                                <span class="ui large black text">
                                    {{ organization.name }} 
                                </span>
                            </div>
                        </a>
                    </div>

                    {% set count = namespace(value=0) %}
                    {% for org in current_user.organizations %}
                        {% if org != organization %}
                            {% if count.value < 1 %}
                                <div class="ui horizontal divider">Your Organization</div>
                            {% endif %}
                            
                            {% set count.value = count.value + 1 %}
                            <a class="item" href="{{ url_for('accounts.change_organization', organization_id=org.id) }}">
                                <div class="ui vertically fitted basic segment">
                                    <div class="ui tiny  header">
                                        <img src="{{ org.get_logo_picture() }}" width="30" height="30" ">
                                        <div class="content">
                                            <span class="ui sub header" style="font-weight: 500 ;">{{ org.name }}</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% if count.value <= 0 %}
                        <div class="disabled item">
                            
                        </div>
                    {% endif %}
                </div>
            </div>
        </h1>
    {% endif %}
{% endmacro %}


{% macro render_organization_dashboard_menu_bar(organization) %}
    {% if 'admin' in request.path %}
        <div class="ui top attached tabular menu">
            <a class="item {{ 'active' if request.endpoint == 'admin.organizations.view' or request.endpoint == 'admin.organizations.view' }}"
                href="{{ url_for('admin.organizations.view', organization_id=organization.id) }}">
                <i class="home icon"></i>Overview
            </a>
            <a  class="item {{ 'active' if 'admin.organizations.view_users' in request.endpoint }}" 
                href="{{ url_for('admin.organizations.view_users', organization_id=organization.id, role='all') }}">
                <i class="users icon"></i>Users
            </a>
            <a  class="item {{ 'active' if 'admin.organizations.view_classes' in request.endpoint }}" 
                href="{{ url_for('admin.organizations.view_classes', organization_id=organization.id) }}">
                <i class="archive icon"></i>Classes
            </a>
            <a  class="item {{ 'active' if 'admin.organizations.view_templates' in request.endpoint }}" 
                href="{{ url_for('admin.organizations.view_templates', organization_id=organization.id)}}">
                <i class="id card icon"></i>Templates
            </a>
            <a  class="item {{ 'active' if 'admin.organizations.view_logos' in request.endpoint }}" 
                href="{{ url_for('admin.organizations.view_logos', organization_id=organization.id)}}">
                <i class="certificate icon"></i>Logos
            </a>
        </div>
    {% else %}
        <div class="ui top attached tabular menu">
            <a class="item {{ 'active' if request.endpoint == 'organizations.view' or request.endpoint == 'organizations.view' }}"
                href="{{ url_for('organizations.view', organization_id=organization.id) }}">
                <i class="home icon"></i>Overview
            </a>
            <a  class="item {{ 'active' if 'organizations.view_users' in request.endpoint }}" 
                href="{{ url_for('organizations.view_users', organization_id=organization.id, role='all') }}">
                <i class="users icon"></i>Users
            </a>
            <a  class="item {{ 'active' if 'organizations.view_classes' in request.endpoint }}" 
                href="{{ url_for('organizations.view_classes', organization_id=organization.id) }}">
                <i class="archive icon"></i>Classes
            </a>
            <a  class="item {{ 'active' if 'organizations.view_templates' in request.endpoint }}" 
                href="{{ url_for('organizations.view_templates', organization_id=organization.id)}}">
                <i class="id card icon"></i>Templates
            </a>
            <a  class="item {{ 'active' if 'organizations.view_logos' in request.endpoint }}" 
                href="{{ url_for('organizations.view_logos', organization_id=organization.id)}}">
                <i class="certificate icon"></i>Logos
            </a>
        </div>
    {% endif %}
{% endmacro %}

viyyoor/web/templates/base/toolbar-dashboard.html
<div class="item">
  <a href="{{ url_for('accounts.index') }}" class="ui image">
    {%- if current_user.get_picture() %}
      <img class="ui avatar image" src="{{ current_user.get_picture() }}">
    {% else %}
      <i class="user icon"></i>
    {% endif -%}
  </a>
  <a href="{{ url_for('accounts.index') }}"><span class="white-text name">{{ current_user.first_name }} {{ current_user.last_name }}</span></a><br/>
  <a href="{{ url_for('accounts.index') }}"><span class="white-text email">{{ current_user.email }}</span></a>
</div>

<a class="item" href="{{ url_for('dashboard.index') }}"><i class="icon dashboard"></i>Dashboard</a>

{% if current_user.has_roles(['admin']) %}
  <a class="item" href="{{ url_for('dashboard.show_my_certificates') }}"><i class="icon dashboard"></i>My Certificate</a>
  <a class="item" href="{{ url_for('admin.index') }}"><i class="icon user shield"></i>Admin</a>
  <a class="item" href="{{ url_for('admin.classes.index') }}"><i class="icon users"></i>Class</a>
  <a class="item" href="{{ url_for('admin.endorsers.index') }}"><i class="icon user check"></i>Endorsers</a>
  <a class="item" href="{{ url_for('admin.templates.index') }}"><i class="icon id card outline"></i>Template</a>
  <a class="item" href="{{ url_for('admin.organizations.logos') }}"><i class="icon id card outline"></i>Logo</a>
  <a class="item" href="{{ url_for('admin.users.index') }}"><i class="icon user"></i>User</a>
  <a class="item" href="{{ url_for('admin.signatures.index') }}"><i class="icon signature file"></i>Signature</a>
  <a class="item" href="{{ url_for('admin.digital_certificates.index') }}"><i class="icon stamp file"></i>Digital Certificate</a>
  <a class="item" href="{{ url_for('admin.certificates.index') }}"><i class="icon certificate file"></i>Certificate</a>
{% endif %}

<a class="item" href="{{ url_for('accounts.index') }}"><i class="address book icon"></i>Account</a>
<a class="item" href="{{ url_for('accounts.logout') }}"><i class="sign out icon"></i>Logout</a>

viyyoor/web/templates/base/toolbar.html
<div class="ui inverted menu" style="background-color: rgb(25, 60, 108);">
  <div class="ui container">
    {# 
    <a class="item" href="{{ url_for('site.index') }}"><img src="{{ url_for('static', filename='images/lotus-full-100px.png') }}" style="padding-right: 5px;"> {{ config.get('APP_TITLE') }}</a>
    #}
    <a class="item" href="{{ url_for('site.index') }}"><img src="{{ url_for('static', filename='images/PSU-logo-white.png') }}" style="padding-right: 5px;"> {{ config.get('APP_TITLE') }}</a>
    <a class="item" href="{{ url_for('accounts.index') }}"><i class="address book icon"></i>Account</a>
    <a class="item" href="{{ url_for('dashboard.index') }}"><i class="dashboard icon"></i>Dashboard</a>
    {#
    <a class="item" href="{{ url_for('tags.index') }}"><i class="tag icon"></i>Tags</a>
    #}
  </div>
</div