viyyoor/web/views/classes.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    Response,
    send_file,
    request,
    current_app,
)
from flask_login import current_user, login_required
import datetime
from urllib import parse

from viyyoor import models
from .. import forms
from .. import acl
from .. import redis_rq

from viyyoor.utils import digital_signature_utils
from viyyoor.utils import certificate_utils

module = Blueprint(
    "classes",
    __name__,
    url_prefix="/classes",
)


@module.route("/")
@login_required
def index():
    enrollments = models.Enrollment.objects(user=current_user._get_current_object())
    return render_template("/classes/index.html", enrollments=enrollments)


@module.route("/<class_id>")
@login_required
def view(class_id):
    class_ = models.Class.objects.get(id=class_id)
    if "admin" in current_user.roles or "endorse" in current_user.roles:
        return render_template("/classes/view_endorse.html", class_=class_)

    return render_template("/classes/view.html", class_=class_)


@module.route("/<class_id>/endorse", methods=["GET", "POST"])
@acl.roles_required("endorser")
def endorse(class_id):
    class_ = models.Class.objects.get(id=class_id)
    # certificates = models.Certificate.objects(class_=class_, status="prerelease")
    # form = forms.classes.EndorsementForm()
    # if not form.validate_on_submit():
    #     return render_template(
    #         "/classes/endorse.html", form=form, class_=class_, certificates=certificates
    #     )

    certificates = models.Certificate.objects(class_=class_, status="prerelease")

    endorsers = class_.get_endorsers_by_user(current_user._get_current_object())
    if not len(endorsers):
        return redirect(url_for("dashboard.index"))

    for certificate in certificates:
        # sign signature hear1
        # sign_digital_signature(user, certificate, password)
        endorsement = models.Endorsement(
            endorser=current_user._get_current_object(),
            ip_address=request.remote_addr,
        )

        for endorser in endorsers:
            certificate.endorsements[endorser.endorser_id] = endorsement

        check_approval = True
        for key, endorser in class_.endorsers.items():
            if endorser.endorser_id not in certificate.endorsements:
                check_approval = False
            elif (
                endorser.endorser_id in certificate.endorsements
                and endorser.user
                != certificate.endorsements[endorser.endorser_id].endorser
            ):
                check_approval = False

            if not check_approval:
                break

        if check_approval:
            certificate.status = "signing"

        certificate.updated_date = datetime.datetime.now()
        certificate.save()

    job = redis_rq.redis_queue.queue.enqueue(
        digital_signature_utils.sign_certificates,
        args=(class_id, current_app.config),
        job_id=f"endorsements_certificates_{class_.id}",
        timeout=600,
        job_timeout=600,
    )

    return redirect(url_for("dashboard.index"))


@module.route("/<class_id>/certificate/<participant_id>.<extension>")
# @login_required
def render_certificate(class_id, participant_id, extension):
    response = Response()
    response.status_code = 404

    class_ = models.Class.objects.get(id=class_id)
    participant = class_.get_participant(participant_id)
    certificate_template = class_.certificate_templates.get(participant.group)

    if not certificate_template:
        return response

    class Organization:
        authenticity_text = current_app.config.get("DEFAULT_AUTHENTICITY_TEXT")

    class_.organization = Organization

    image_io = certificate_utils.render_certificate(
        class_,
        participant_id,
        extension,
        validated_url_template=request.host_url[:-1]
        + parse.unquote(
            url_for("certificates.view", certificate_id="{certificate_id}")
        ),
    )

    if extension in ["png", "svg"]:
        mimetype = f"image/{extension}"
    elif extension == "pdf":
        mimetype = "application/pdf"

    response = send_file(
        image_io,
        download_name=f"{class_.id}-{participant_id}.{extension}",
        # as_attachment=True,
        mimetype=mimetype,
    )

    return response

viyyoor/web/views/organization.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    send_file,
    Response,
)
from flask_login import current_user, login_required

import datetime

from viyyoor.web import acl, forms
from viyyoor import models


module = Blueprint("organizations", __name__, url_prefix="/organizations")


@module.route("/")
def index():
    organizations = models.Organization.objects(
        status="active",
    )
    return render_template(
        "/admin/organizations/index.html",
        now=datetime.datetime.now,
        organizations=organizations,
    )


@module.route("/<organization_id>")
@acl.roles_required("admin")
def view(organization_id):
    organization = models.Organization.objects.get(
        id=organization_id,
        status="active",
    )
    logos = models.CertificateLogo.objects()
    classes = models.Class.objects(organization=organization, status="active")
    return render_template(
        "/admin/organizations/view.html",
        logos=logos,
        organization=organization,
        classes=classes,
    )


@module.route("/logos/<logo_id>/download/<filename>")
def download_logo(logo_id, filename):
    response = Response()
    response.status_code = 404
    logo = models.CertificateLogo.objects.get(id=logo_id)

    if logo:
        response = send_file(
            logo.logo_file,
            download_name=filename,
            mimetype=logo.logo_file.content_type,
        )

    return response

viyyoor/web/views/organizations.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    send_file,
    Response,
)
from flask_login import current_user, login_required

import datetime

from viyyoor.web import acl, forms
from viyyoor import models


module = Blueprint("organizations", __name__, url_prefix="/organizations")


@module.route("/")
def index():
    organizations = models.Organization.objects(
        status="active",
    )
    return render_template(
        "/organizations/index.html",
        now=datetime.datetime.now,
        organizations=organizations,
    )


@module.route("/<organization_id>")
@acl.organization_roles_required("admin", "endorser", "staff")
def view(organization_id):
    organization = models.Organization.objects.get(
        id=organization_id,
        status="active",
    )
    logos = models.Logo.objects(organization=organization)
    classes = models.Class.objects(organization=organization, status="active")
    return render_template(
        "/organizations/view.html",
        logos=logos,
        organization=organization,
        classes=classes,
    )


@module.route("/<organization_id>/edit", methods=["GET", "POST"])
@acl.organization_roles_required("admin")
def edit(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    form = forms.organizations.AdminOrganizationEditForm()

    if not form.validate_on_submit():
        form.name.data = organization.name
        form.description.data = organization.description
        return render_template(
            "/organizations/edit.html", organization=organization, form=form
        )

    form.populate_obj(organization)
    organization.save()

    return redirect(url_for("organizations.view", organization_id=organization_id))


@module.route("/logos/<logo_id>/download/<filename>")
def download_logo(logo_id, filename):
    response = Response()
    response.status_code = 404
    logo = models.Logo.objects.get(id=logo_id)

    if logo:
        response = send_file(
            logo.logo_file,
            download_name=filename,
            mimetype=logo.logo_file.content_type,
        )

    return response


@module.route(
    "/<organization_id>/logos/<logo_id>/set_as_organization_logo", methods=["POST"]
)
@acl.organization_roles_required("admin")
def change_organization_logo(organization_id, logo_id):
    organization = models.Organization.objects.get(id=organization_id)
    old_logo = models.CertificateLogo.objects(
        organization=organization, marked_as_organization_logo=True
    ).first()
    if old_logo:
        old_logo.marked_as_organization_logo = False
        old_logo.last_updated_by = current_user._get_current_object()
        old_logo.updated_date = datetime.datetime.now()
        old_logo.save()

    new_logo = models.Logo.objects.get(id=logo_id)
    new_logo.marked_as_organization_logo = True
    new_logo.last_updated_by = current_user._get_current_object()
    new_logo.updated_date = datetime.datetime.now()
    new_logo.save()

    return redirect(url_for("organizations.view", organization_id=organization.id))


@module.route("/<organization_id>/classes", methods=["GET", "POST"])
@acl.organization_roles_required("admin", "endorser", "staff")
def view_classes(organization_id):
    organization = models.Organization.objects.get(
        id=organization_id,
        status="active",
    )
    classes = models.Class.objects(organization=organization, status="active")
    return render_template(
        "/organizations/classes.html",
        organization=organization,
        classes=classes,
    )


@module.route("/<organization_id>/logos", methods=["GET", "POST"])
@acl.organization_roles_required("admin", "endorser", "staff")
def view_logos(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    logos = models.Logo.objects(organization=organization)
    return render_template(
        "/organizations/logos.html",
        organization=organization,
        logos=logos,
    )


@module.route("/<organization_id>/users", methods=["GET", "POST"])
@acl.organization_roles_required("admin", "endorser", "staff")
def view_users(organization_id):
    organization = models.organizations.Organization.objects.get(id=organization_id)
    role = request.args.get("role")
    organization_user_roles = organization.get_users()
    if role not in ["all", None]:
        organization_user_roles = organization_user_roles.filter(role=role)
    if request.args.get("status") == "disactive":
        organization_user_roles = models.OrganizationUserRole.objects(
            status="disactive", organization=organization
        )

    org_user_forms = {}
    for u in organization_user_roles:
        org_user_forms[u.id] = forms.organizations.OrganizationRoleSelectionForm(obj=u)

    if request.args.get("user_role_id"):
        user_role = models.OrganizationUserRole.objects.get(
            id=request.args.get("user_role_id")
        )
        form = org_user_forms[user_role.id]
        if form.validate_on_submit():
            user_role.role = form.role.data
            user_role.save()
            return redirect(
                url_for(
                    "organizations.view_users",
                    organization_id=organization.id,
                    role=role,
                )
            )

    add_member_form = forms.organizations.OrgnaizationAddMemberForm()
    add_member_form.members.choices = [
        (str(u.id), u.get_fullname())
        for u in models.User.objects(organizations__nin=[organization])
    ]

    return render_template(
        "/organizations/users.html",
        organization=organization,
        organization_user_roles=organization_user_roles,
        role=role,
        org_user_forms=org_user_forms,
        add_member_form=add_member_form,
    )


@module.route("/<organization_id>/users/submit_add_members", methods=["POST"])
@acl.organization_roles_required("admin")
def submit_add_members(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    form = forms.organizations.OrgnaizationAddMemberForm()
    form.members.choices = [
        (str(u.id), u.get_fullname())
        for u in models.User.objects(organizations__nin=[organization])
    ]

    if not form.validate_on_submit():
        return redirect(
            url_for("organizations.view_users", organization_id=organization.id)
        )

    for u in form.members.data:
        user = models.User.objects.get(id=u)
        user.organizations.append(organization)
        if not user.get_current_organization():
            user.user_setting.current_organization = organization
        user.save()

        org_user = models.OrganizationUserRole(
            organization=organization,
            user=user,
            added_by=current_user._get_current_object(),
            last_modifier=current_user._get_current_object(),
        )
        org_user.save()

    return redirect(
        url_for("organizations.view_users", organization_id=organization.id)
    )


@module.route(
    "/<organization_id>/users/<organization_user_id>/<operator>",
    methods=["GET", "POST"],
)
@acl.organization_roles_required("admin")
def manage_user(organization_id, organization_user_id, operator):
    organization = models.Organization.objects.get(id=organization_id)
    organization_user = models.OrganizationUserRole.objects.get(id=organization_user_id)

    if operator == "deactivate":
        organization_user.status = "disactive"
    elif operator == "activate":
        organization_user.status = "active"
    elif operator == "delete":
        user = organization_user.user
        user.organizations.remove(organization)
        if user.get_current_organization() == organization:
            user.user_setting.current_organization = None
        user.save()
        organization_user.delete()

    organization_user.last_modifier = current_user._get_current_object()
    organization_user.updated_date = datetime.datetime.now()
    organization_user.last_ip_address = request.headers.get(
        "X-Forwarded-For", request.remote_addr
    )
    organization_user.save()

    print(operator, "user", organization_user.user.first_name)
    return redirect(
        url_for(
            "organizations.view_users",
            organization_id=organization.id,
            role="all",
        )
    )


@module.route("/<organization_id>/logos/add", methods=["GET", "POST"])
@acl.organization_roles_required("staff, admin")
def add_logo(organization_id):
    organization = models.Organization.objects.get(id=organization_id)
    logo = models.CertificateLogo()
    form = forms.organizations.OrganizationLogoForm()

    if not form.validate_on_submit():
        print(form.errors)
        return render_template(
            "/organizations/add-logo.html",
            organization=organization,
            form=form,
        )

    form.populate_obj(logo)

    if logo.logo_file:
        logo.logo_file.put(
            form.uploaded_logo_file.data,
            filename=form.uploaded_logo_file.data.filename,
            content_type=form.uploaded_logo_file.data.content_type,
        )

    else:
        logo.logo_file.replace(
            form.uploaded_logo_file.data,
            filename=form.uploaded_logo_file.data.filename,
            content_type=form.uploaded_logo_file.data.content_type,
        )

    logo.organization = organization
    logo.uploaded_by = current_user._get_current_object()
    logo.uploaded_date = datetime.datetime.now()
    logo.save()

    return redirect(
        url_for("organizations.view_logos", organization_id=organization_id)
    )


@module.route("/<organization_id>/<logo_id>/delete")
@acl.organization_roles_required("admin")
def delete_logo(organization_id, logo_id):
    organization = models.Organization.objects.get(id=organization_id)
    logo = models.CertificateLogo.objects.get(id=logo_id)
    logo.delete()

    return redirect(

viyyoor/web/templates/dashboard/index-admin.html
{% extends '/base/default-dashboard.html' %}

{% block additional_js %}
<script>
  $('.ui.big.breadcrumb')[0].parentElement.style.display = "none"
  
  const links = document.querySelectorAll('.blinking.link')
  links.forEach((link, index) => {
    link.setAttribute('onmouseover', 'this.style.color="#2185d0"');
    link.setAttribute('onmouseout', 'this.style.color="black"');
  });

  const secondaryLinks = document.querySelectorAll('.secondary.link')
  secondaryLinks.forEach((link, index) => {
    link.setAttribute('onmouseover', 'this.style.color="#4797d4"');
    link.setAttribute('onmouseout', 'this.style.color="rgba(0,0,0,.4)"');
  });
</script>

{% endblock%}

{% block content %}
  {% set organization = current_user.get_current_organization() %}
  {% if organization %}
      <h2 class="ui header" style="color:#4797d4">
        <img src="{{ organization.get_logo_picture() }}" width="120" height="120" style="object-fit: contain;">
        <div class="content">
          <a class="ui header blinking link" href="{{ url_for('organizations.view', organization_id=organization.id) }}">
            {{ organization.name }}
          </a>
          <div class="sub header">{{ organization.description }}</div>
        </div>        
      </h2>
      <div class="ui divider"></div>

      <div class="ui centered cards">
          <div class="ui card" style="width: 16em; margin-right: 1em">
            <div class="content" style="margin: 0.5em">
              <div class="header">
                <span class="ui big psu-deep-blue text">
                  {{ organization.get_users().count() }}
                </span>
                <i class="  right floated users large icon" style="margin-top: 0.5em"></i>
              </div>
              <div class="meta">
                <span class="ui black large text">
                  Member
                </span>
              </div>
            </div>
            <a class="ui fluid psu-deep-blue button" href="{{ url_for('organizations.view_users', organization_id=organization.id) }}">
              View
            </a>
          </div>

          <div class="ui card" style="width: 16em; margin-right: 1em">
              <div class="content" style="margin: 0.5em">
                <div class="header">
                  <span class="ui big psu-andaman-blue text">
                    {{ organization.get_classes().count() }}
                  </span>
                  <i class="right floated archive large icon" style="margin-top: 0.5em"></i>
                </div>
                <div class="meta">
                  <span class="ui black large text">
                    Class
                  </span>
                </div>
              </div>
              <a class="ui fluid psu-andaman-blue button" href="{{ url_for('organizations.view_classes', organization_id=organization.id) }}">
                View
              </a>
          </div>

          
          <div class="ui card" style="width: 16em; margin-right: 1em">
            <div class="content" style="margin: 0.5em">
              <div class="header">
                <span class="ui big psu-sky-blue text">
                  {{ organization.get_templates().count() }}
                </span>
                <i class="right floated id card large icon" style="margin-top: 0.5em"></i>
              </div>
              <div class="meta">
                <span class="ui black large text">
                  Template
                </span>
              </div>
            </div>
            <a class="ui fluid psu-sky-blue button" href="{{ url_for('organizations.view_templates', organization_id=organization.id) }}">
              View
            </a>
        </div>

        <div class="ui card" style="width: 16em; margin-right: 1em">
          <div class="content" style="margin: 0.5em">
            <div class="header">
              <span class="ui big psu-river-blue text">
                {{ organization.get_logos().count() }}
              </span>
              <i class="right floated brush icon large icon" style="margin-top: 0.5em"></i>
            </div>
            <div class="meta">
              <span class="ui black large text">
                Logo
              </span>
            </div>
          </div>
          <a class="ui fluid psu-river-blue button" href="{{ url_for('organizations.view_logos', organization_id=organization.id) }}">
            View
          </a>
        </div>
      </div>
      <br>
  {% endif %}

{% if 'endorser' in current_user.roles %}
  <h1 class="ui horizontal header divider">
    Endorsement
  </h1>
  {% if not endorses_classes %}
    <div class="ui horizontal divider" style="margin: 3em 40% 3em 40%"><span style="color: rgb(172, 172, 172);">Waiting for new endorsement</span> </div>
    {% else %}
    <div class="ui cards">
      {% for class_ in endorses_classes %}
      <div class="green card">
        <div class="content">
          <div class="header">
            <a class="ui header blinking link" href="{{ url_for('classes.view', class_id=class_.id) }}">
              {{ class_.name }}
            </a>
          </div>
          <div class="meta">
            <a href="{{ url_for('organizations.view', organization_id=class_.organization.id) }}" class="secondary link">
              {{ class_.organization.name }}
            </a>
          </div>
          <div class="description">
            {{ class_.description }}
          </div>
        </div>
        <div class="extra content">
          <div class="ui sub header"><span class="ui grey text">Endorser</span></div>
          {% for key, endorser in class_.endorsers.items() %}
          <i class="small user icon"></i>{{ endorser.user.first_name }} {{ endorser.user.last_name }} <br>
        {% endfor %}
        </div>
        <div class="extra content">
            <a class="ui fluid basic green button" href="{{ url_for('classes.endorse', class_id=class_.id) }}">
              Endorse
            </a>
        </div>
      </div>
      {% endfor %}
    </div>
  {% endif %}
  

  
  <h2 class="ui horizontal header divider">
    Last Endorsement
  </h2>
  {% if not endorsed_classes %}
  <div class="ui horizontal divider" style="margin: 3em 36% 3em 36%">
    <span style="color: rgb(172, 172, 172);">
      you don't have any endorsement
    </span> 
  </div>
  {% else %}
  <div class="ui cards">
    {% for class_ in endorsed_classes %}
    {% set job = endorsed_jobs[ class_.id| string] %}
    {% if job %}
    <div class="{{ 'red' if job.get_status(refresh=True) == 'failed' }}
                {{ 'yellow' if job.get_status(refresh=True) in ['queued', 'started']}}
                {{ '' if job.get_status(refresh=True) == 'finished'}}
                card">
    {% else %}
    <div class="green card">
    {% endif %}
      <div class="content">
        <div class="header">
          <a class="ui header blinking link" href="{{ url_for('classes.view', class_id=class_.id) }}">
            {{ class_.name }}
          </a>
        </div>
        <div class="meta">
          <a class="secondary link" href="{{ url_for('organizations.view', organization_id=class_.organization.id) }}">
            {{ class_.organization.name }}
          </a>
        </div>
        <div class="description">
          {{ class_.description }}
        </div>
      </div>
      <div class="extra content">
        <div class="ui sub header"><span class="ui grey text">Endorser</span></div>
        {% for key, endorser in class_.endorsers.items() %}
        <i class="small user icon"></i>{{ endorser.user.first_name }} {{ endorser.user.last_name }} <br>
      {% endfor %}
      </div>
      <div class="extra left aligned content">
          <div class="ui sub header">Status</div>
          
          {% if job %}
            {% if job.get_status(refresh=True) in ["queued", "started"] %}
              <div class="ui label yellow" >{{ job.get_status(refresh=True).title() }}</div>
            {% elif job.get_status(refresh=True) in ["failed"] %}
              <div class="ui label red" >{{ job.get_status(refresh=True).title() }}</div>
            {% else %}
              <div class="ui orange label" >{{ job.get_status(refresh=True).title() }}</div>
            {% endif %}
          {% else %}
            <div class="ui label green">Completed</div>
          {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}
{% endif %}

{% endblock %}

viyyoor/web/templates/dashboard/index-user.html
{% extends '/base/default-dashboard.html' %}

{% block content %}
<div class="ui segment middle algined" style="min-height: 80vh; padding-top: 10vh">
  <div class="ui icon header center aligned">
    <i class="icon university end"></i>
    <h3>Hello, {{ current_user.first_name }} {{ current_user.last_name }} </h3>
  </div>
  <div>
    <div class="ui cards">
      {% for certificate in certificates: %}
      <div class="card">
        <div class="content">
          <div class="header">{{ certificate.class_.name }}</div>
          <div class="description">
            {% if certificate.class_.instructors %}
              <p><b>Instructor: </b> {{ certificate.class_.instructors | join(',') }}</p>
            {% endif %}
            {% if 'project_name' in certificate.get_participant().extra %}
              <p><b>Project: </b> {{ certificate.get_participant().extra['project_name'] }}</p>
            {% endif %}
              <p><b>Issued Date: </b> {{ certificate.issued_date }}</p>
            <p>{{ certificate.class_.description }}</p>
          </div>
        </div>
        <a class="ui bottom attached primary button" href="{{ url_for('certificates.view', certificate_id=certificate.id) }}" target="_blank">
          <i class="certificate icon"></i>
          View
        </a>
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}